### ISSUE TITLE
The Linux Foundation announcement August 11

### ISSUE THREAD

**Issue by andygrillo** [openeew/openeew#9]

**Comment by krook** [comment]
Adding this guidance:

These are the suggestions made in order to build a community of end-users and contributors around your Linux Foundation winning project:

- [x] Add the Apache 2 LICENSE.md to your GitHub repository and include the specific copyright header to your source code files using the relevant comment syntax for the programming language. Add the license file as is, then use 2018 and list the names of your team members in your individual source files. http://www.apache.org/licenses/LICENSE-2.0#apply
- [x] Look at improving your documentation so that first-time visitors clearly see the problem you are solving and how they can understand the solution in your README.md. Also consider enabling alternative language translations.
- [ ] Look at carefully documenting installation/duplication steps so that new developers can explore the technology on their own systems in order to contribute back fixes. This will also help you identify any potential dependency issues you might have on clean installations.
- [x] Add a basic CONTRIBUTING.md that describes how others can start to collaborate with you. The Linux Foundation has a few sample files you can use for inspiration. The way you choose to accept fixes is up to you though. Here's a good sample: https://github.com/nodejs/node/blob/master/CONTRIBUTING.md 
- [ ] Strongly consider adding the Developer Certificate of Origin bot to your repositories. This provides assurance that anyone who contributes to your repository has the rights to the code they want to provide: https://github.com/apps/dco 
- [x] Consider configuring GitHub pages to create a basic description and FAQ site, like https://gql.foundation/
- [x] Customize the project charter template from The Linux Foundation

You can see an example of all these things here: https://github.com/Call-for-Code/project-sample

**Comment by andygrillo** [comment]
excellent guide, thanks.
